Gcode Class Reference
The Gcode class provides functions for generating G-code instructions.
#include <Gcode.h>
Static Public Member Functions
static void StartGcode (std::ofstream &gcode)
Writes one layer of the sliced 3D model into gcode.
static void WriteGcode (std::ofstream &ofs, std::vector< Section > const &sections)
static void CloseGcode (std::ofstream &gcode)
static void SortSections (std::vector< Section > &sections)
Sorts the sections in order to create a continuous path for the printer.
Detailed Description
The Gcode class provides functions for generating G-code instructions.
Definition at line 13 of file Gcode.h.
Member Function Documentation
CloseGcode()
void Gcode::CloseGcode (std::ofstream & gcode) [static]
Definition at line 35 of file Gcode.cpp.
                                         {
    std::string stop = "G28 X0 Y0;";
    gcode << stop << std::endl;
    gcode.close();
}
Referenced by main().
SortSections()
void Gcode::SortSections (std::vector< Section > & sections) [static]
Sorts the sections in order to create a continuous path for the printer.
Parameters
sections The vector of sections to be sorted.
Definition at line 8 of file Gcode.cpp.
                                                     {
    // Select the first section
    for (unsigned i = 0; i < sections.size(); i++) {
        for (unsigned j = i + 1; j < sections.size(); j++) {
            if (sections[i] <<= sections[j]) { // If the two sections can be concatenated
                // Swap sections[j] with sections[i+1]
                std::swap(sections[i + 1], sections[j]);
            }
        }
    }
}
Referenced by main().
StartGcode()
void Gcode::StartGcode (std::ofstream & gcode) [static]
Writes one layer of the sliced 3D model into gcode.
Parameters
ofs The output stream to write the G-code to.
sections The vector of sections to generate G-code from.
Definition at line 29 of file Gcode.cpp.
                                         {
    std::string start = "G28;Home\nG1 Z20 F6000;Move the platform down 20mm\n";
    gcode << start << std::endl;
}
Referenced by main().
WriteGcode()
void Gcode::WriteGcode (std::ofstream & ofs, std::vector< Section > const & sections) [static]
Definition at line 21 of file Gcode.cpp.
                                                                            {
    unsigned i;
    for (i = 0; i < sections.size(); i++) {
        gcode << "G1 F1500" << sections[i] << " E" << (i + 1) << std::endl;
    }
}
Referenced by main().
The documentation for this class was generated from the following files:
STL_SLICER/include/Gcode.h
STL_SLICER/src/Gcode.cpp