Section Class Reference
Represents a section defined by two vectors.
#include <Section.h>
Public Member Functions
Section (Vector v1=Vector(), Vector v2=Vector())
Default constructor for Section.
Vector PlaneInterSection (const Plane &plane, bool &isValidPoint) const
Calculates the intersection point between the section and a plane.
void print (std::ostream &os=std::cout) const
Prints the section to the specified output stream.
bool operator== (const Section &other) const
Checks if two sections are equal.
bool operator<<= (Section &other) const
Checks if the two vectors connect and have the same direction.
Detailed Description
Represents a section defined by two vectors.
Definition at line 9 of file Section.h.
Constructor & Destructor Documentation
Section()
Section::Section (Vector v1 = Vector(), Vector v2 = Vector())
Default constructor for Section.
Parameters
v1 The first vector of the section.
v2 The second vector of the section.
Definition at line 22 of file Section.cpp.
                                     {
    // Initialize the section with two vectors
    section[0] = v1;
    section[1] = v2;
}
Member Function Documentation
operator<<=()
bool Section::operator<<= (Section & other) const
Checks if the two vectors connect and have the same direction.
Parameters
other The other section to compare with.
Returns
True if the endpoint of the first vector is equal to the starting point of the second vector.
Definition at line 55 of file Section.cpp.
                                           {
    if (section[1] == rs.section[1]) {
        // If the sections are facing each other, swap the coordinates of rs
        Vector tmp = rs.section[0];
        rs.section[0] = rs.section[1];
        rs.section[1] = tmp;
    }
    return section[1] == rs.section[0]; // Return true if v2 = rs.v1
}
operator==()
bool Section::operator== (const Section & other) const
Checks if two sections are equal.
Parameters
other The other section to compare with.
Returns
True if the sections are equal, false otherwise.
Definition at line 48 of file Section.cpp.
                                                   {
    // Check if two sections are equal by comparing their vectors
    return section[0] == other.section[0] && section[1] == other.section[1];
}
PlaneInterSection()
Vector Section::PlaneInterSection (const Plane & plane, bool & isValidPoint) const
Calculates the intersection point between the section and a plane.
Parameters
plane The plane to intersect with.
success Indicates if the intersection was successful.
Returns
The intersection point as a Vector.
Definition at line 7 of file Section.cpp.
                                                                              {
    // Calculate the intersection point between the section and a plane
    // using the formula: t = dot(ref_point - v1, normal) / dot(v2 - v1, normal)
    double t = Vector::dot(plane.getRef() - section[0], plane.getNormal()) /
        Vector::dot((section[1] - section[0]), plane.getNormal());
    if (t <= 0 || t >= 1) {
        isValidPoint = false;
    }
    // Calculate the intersection point
    Vector result = section[0] + Vector((section[1] - section[0]) * t);
    return result;
}
References Vector::dot(), Plane::getNormal(), and Plane::getRef().
Referenced by main(), and Facet::PlaneIntersection().
print()
void Section::print (std::ostream & os = std::cout) const
Prints the section to the specified output stream.
Parameters
os The output stream to print to.
Definition at line 29 of file Section.cpp.
                                        {
    if (&os != &std::cout) {
        // If writing to a file, only output the second vector of the section
        os << section[1];
    }
    else {
        // If writing to std::cout, output both vectors of the section
        os << "Section v1:" << section[0] << " ,v2:" << section[1];
    }
}
Referenced by operator<<().
The documentation for this class was generated from the following files:
C:/Users/krisz/Documents/GitHub/STL_Slicer/STL_SLICER/include/Section.h
C:/Users/krisz/Documents/GitHub/STL_Slicer/STL_SLICER/src/Section.cpp