STLFile Class Reference
The STLFile class represents an STL file.
#include <STLFile.h>
Static Public Member Functions
static std::vector< Facet > readSTLFile (const std::string &filename)
Reads the STL file in binary or text format.
static bool isBinarySTL (const std::string &filename)
Checks if the file is in binary STL format.
Static Public Attributes
static double minZ = 0
static double maxZ = 0
Detailed Description
The STLFile class represents an STL file.
Definition at line 10 of file STLFile.h.
Member Function Documentation
isBinarySTL()
bool STLFile::isBinarySTL (const std::string & filename) [static]
Checks if the file is in binary STL format.
Checks if an STL file is in binary format.
Parameters
filename The path to the STL file.
Returns
True if the file is in binary format, false otherwise.
Parameters
filename The name of the STL file to check.
Returns
true if the file is in binary format, false otherwise.
Definition at line 109 of file STLFile.cpp.
                                                   {
    std::ifstream file(filename, std::ios::in | std::ios::binary);
    if (!file) {
        throw std::runtime_error("Could not open file: " + filename);
    }
    char header[6];
    file.read(header, 6);
    return std::string(header, 6) != "solid "; // Check if stl file is in binary mode
}
Referenced by readSTLFile().
readSTLFile()
std::vector< Facet > STLFile::readSTLFile (const std::string & filename) [static]
Reads the STL file in binary or text format.
Reads an STL file and returns a vector of facets.
Parameters
filename The path to the STL file.
Returns
A vector of Facet objects representing the facets in the STL file.
Parameters
filename The name of the STL file to read.
Returns
std::vector<Facet> A vector containing the facets read from the file.
Definition at line 14 of file STLFile.cpp.
                                                               {
    std::vector<Facet> facets; // Create a vector to store the facets (this will dynamically grow)
    if (isBinarySTL(filename))
    {
        std::ifstream stl_file(filename, std::ios::binary);
        if (!stl_file.is_open()) {
            throw std::runtime_error("Could not open file: " + filename);
            return facets;
        }
        // Read the header (80 bytes) and ignore it
        stl_file.ignore(80);
        // Read the number of facets (4 bytes)
        uint32_t numFacets;
        stl_file.read(reinterpret_cast<char*>(&numFacets), sizeof(numFacets));
        // Read each facet
        for (uint32_t i = 0; i < numFacets; i++) {
            // Read the normal vector (12 bytes)
            float normal[3];
            stl_file.read(reinterpret_cast<char*>(&normal), sizeof(normal));
            // Read the vertices (36 bytes)
            Vector vertices[3];
            float xyz[3];
            for (int j = 0; j < 3; j++) {
                stl_file.read(reinterpret_cast<char*>(&xyz), sizeof(xyz));
                vertices[j].convert(xyz);
                if (vertices[j] < minZ) {
                    minZ >> vertices[j];
                }
                if (vertices[j] > maxZ) {
                    maxZ >> vertices[j];
                }
            }
            // Skip the attribute byte count (2 bytes)
            stl_file.ignore(2);
            Facet facet(vertices[0], vertices[1], vertices[2]);
            facets.push_back(facet);
        }
        stl_file.close();
    }
    else//Read file in text format
    {
        std::ifstream stl_file(filename);
        if (!stl_file.is_open()) {
            throw std::runtime_error("Could not open file: " + filename);
            return facets;
        }
        std::string line;
        while (std::getline(stl_file, line)) { // Read each line
            Vector xyz[3];
            if (line.find("facet normal") != std::string::npos) {
                //
                //std::istringstream sin(line.substr(line.find("facet normal") + 12)); // Initialize with the part after "facet normal"
                //sin >> n; // overloaded >> operator
                std::getline(stl_file, line); // Skip "outer loop"
                for (int i = 0; i < 3; i++) {
                    std::getline(stl_file, line); // Read vertex
                    std::istringstream sin(line.substr(line.find("vertex") + 6)); // Initialize with the part after "facet normal"
                    sin >> xyz[i];
                    if (xyz[i] < minZ) {
                        minZ >> xyz[i];//"beletöltöm a Vector >> operatorral a koordinatat"
                    }
                    if (xyz[i] > maxZ) {
                        maxZ >> xyz[i];
                    }
                }
                std::getline(stl_file, line); // Skip "endloop"
                std::getline(stl_file, line); // Skip "endfacet"
                Facet facet(xyz[0], xyz[1], xyz[2]);
                facets.push_back(facet);
            }
        }
        stl_file.close();
    }
    return facets;
}
References Vector::convert(), isBinarySTL(), maxZ, minZ, and Vector::read().
Referenced by main().
Member Data Documentation
maxZ
double STLFile::maxZ = 0 [static]
The maximum Z coordinate value in the STL file.
Definition at line 14 of file STLFile.h.
Referenced by main(), and readSTLFile().
minZ
double STLFile::minZ = 0 [static]
The minimum Z coordinate value in the STL file.
Definition at line 13 of file STLFile.h.
Referenced by main(), and readSTLFile().
The documentation for this class was generated from the following files:
STL_SLICER/include/STLFile.h
STL_SLICER/src/STLFile.cpp