Vector Class Reference
The Vector class represents a 3D vector.
#include <Vector.h>
Public Member Functions
Vector (double x=0, double y=0, double z=0)
Constructor for the Vector class.
double getLength () const
Returns the length of the Vector.
void print (std::ostream &os=std::cout) const
Prints out a Vector to the output stream.
void read (std::istream &is=std::cin)
Reads a Vector from input stream.
Vector operator- (const Vector &v) const
Subtracts two Vectors: v1 - v2.
Vector operator+ (const Vector &v) const
Adds two Vectors together: v1 + v2.
bool operator< (double &d) const
Compares the z coordinate with a double.
bool operator> (double &d) const
Compares the z coordinate with a double.
Vector & operator* (double scalar)
Multiply all the coordinates with a scalar value.
bool operator== (const Vector &v) const
Compares two Vectors.
void convert (const float *arr)
Converts the coordinates from float array to double.
Static Public Member Functions
static double dot (const Vector &v1, const Vector &v2)
Calculates the dot product of two Vectors.
static Vector cross (const Vector &v1, const Vector &v2)
Calculates the cross product of two Vectors.
Friends
void operator>> (double &d, Vector const &v)
Streams the Z coordinate into the double.
Detailed Description
The Vector class represents a 3D vector.
Definition at line 7 of file Vector.h.
Constructor & Destructor Documentation
Vector()
Vector::Vector (double x = 0, double y = 0, double z = 0) [inline]
Constructor for the Vector class.
Parameters
x The x-coordinate of the vector.
y The y-coordinate of the vector.
z The z-coordinate of the vector.
Definition at line 20 of file Vector.h.
    {
        XYZ[0] = x;
        XYZ[1] = y;
        XYZ[2] = z;
    };
Referenced by cross(), operator+(), and operator-().
Member Function Documentation
convert()
void Vector::convert (const float * arr)
Converts the coordinates from float array to double.
Convert a float array to a Vector.
Parameters
arr The float array containing the coordinates.
arr The float array.
Definition at line 151 of file Vector.cpp.
                                     {
    XYZ[0] = static_cast<double>(arr[0]);
    XYZ[1] = static_cast<double>(arr[1]);
    XYZ[2] = static_cast<double>(arr[2]);
}
Referenced by STLFile::readSTLFile().
cross()
Vector Vector::cross (const Vector & n1, const Vector & n2) [static]
Calculates the cross product of two Vectors.
Calculate the cross product of two vectors.
Parameters
v1 The first Vector.
v2 The second Vector.
Returns
The cross product of the two Vectors.
Parameters
n1 The first vector.
n2 The second vector.
Returns
The cross product of the two vectors.
Definition at line 31 of file Vector.cpp.
                                                       {
    return Vector(n1.XYZ[1] * n2.XYZ[2] - n1.XYZ[2] * n2.XYZ[1],
        n1.XYZ[2] * n2.XYZ[0] - n1.XYZ[0] * n2.XYZ[2],
        n1.XYZ[0] * n2.XYZ[1] - n1.XYZ[1] * n2.XYZ[0]);
}
References Vector().
Referenced by main().
dot()
double Vector::dot (const Vector & v1, const Vector & v2) [static]
Calculates the dot product of two Vectors.
Calculate the dot product of two vectors.
Parameters
v1 The first Vector.
v2 The second Vector.
Returns
The dot product of the two Vectors.
Parameters
v1 The first vector.
v2 The second vector.
Returns
The dot product of the two vectors.
Definition at line 21 of file Vector.cpp.
                                                     {
    return v1.XYZ[0] * v2.XYZ[0] + v1.XYZ[1] * v2.XYZ[1] + v1.XYZ[2] * v2.XYZ[2];
}
Referenced by main(), and Section::PlaneInterSection().
getLength()
double Vector::getLength () const
Returns the length of the Vector.
Calculate the length of the vector.
Returns
The length of the Vector.
The length of the vector.
Definition at line 11 of file Vector.cpp.
                               {
    return std::sqrt(XYZ[0] * XYZ[0] + XYZ[1] * XYZ[1] + XYZ[2] * XYZ[2]);
}
Referenced by main().
operator*()
Vector & Vector::operator* (double t)
Multiply all the coordinates with a scalar value.
Multiply the vector by a scalar value.
Parameters
scalar The scalar value to multiply with.
Returns
The resulting Vector.
Parameters
t The scalar value.
Returns
The resulting vector.
Definition at line 131 of file Vector.cpp.
                                  {
    XYZ[0] *= t;
    XYZ[1] *= t;
    XYZ[2] *= t;
    return *this;
}
operator+()
Vector Vector::operator+ (const Vector & B) const
Adds two Vectors together: v1 + v2.
Overload the + operator to add two vectors.
Parameters
v The Vector to add.
Returns
The resulting Vector.
Parameters
B The vector to be added.
Returns
The resulting vector.
Definition at line 95 of file Vector.cpp.
                                              {
    return Vector(XYZ[0] + B.XYZ[0], XYZ[1] + B.XYZ[1], XYZ[2] + B.XYZ[2]);
}
References Vector().
operator-()
Vector Vector::operator- (const Vector & B) const
Subtracts two Vectors: v1 - v2.
Overload the - operator to subtract two vectors.
Parameters
v The Vector to subtract.
Returns
The resulting Vector.
Parameters
B The vector to be subtracted.
Returns
The resulting vector.
Definition at line 86 of file Vector.cpp.
                                              {
    return Vector(XYZ[0] - B.XYZ[0], XYZ[1] - B.XYZ[1], XYZ[2] - B.XYZ[2]);
}
References Vector().
operator<()
bool Vector::operator< (double & n) const
Compares the z coordinate with a double.
Overload the < operator to compare the Z component of the vector with a double.
Parameters
d The double to compare with.
Returns
True if the z coordinate is less than the double, false otherwise.
Parameters
n The double value to be compared with.
Returns
True if the Z component is less than n, false otherwise.
Definition at line 104 of file Vector.cpp.
                                      {
    return XYZ[2] < n;
}
operator==()
bool Vector::operator== (const Vector & v) const
Compares two Vectors.
Check if two vectors are equal within a small epsilon value.
Parameters
v The Vector to compare with.
Returns
True if the two Vectors are equal, false otherwise.
Parameters
v The vector to be compared with.
Returns
True if the vectors are equal, false otherwise.
Definition at line 143 of file Vector.cpp.
                                             {
    return (std::abs(v.XYZ[0] - XYZ[0]) < epsilon && std::abs(v.XYZ[1] - XYZ[1]) < epsilon && std::abs(v.XYZ[2] - XYZ[2]) < epsilon);
}
References epsilon.
operator>()
bool Vector::operator> (double & n) const
Compares the z coordinate with a double.
Overload the > operator to compare the Z component of the vector with a double.
Parameters
d The double to compare with.
Returns
True if the z coordinate is greater than the double, false otherwise.
Parameters
n The double value to be compared with.
Returns
True if the Z component is greater than n, false otherwise.
Definition at line 113 of file Vector.cpp.
                                      {
    return XYZ[2] > n;
}
print()
void Vector::print (std::ostream & os = std::cout) const
Prints out a Vector to the output stream.
Print the vector to the output stream.
Parameters
os The output stream.
Definition at line 41 of file Vector.cpp.
                                       {
    if (&os != &std::cout) {
        // If the output stream is not cout, we use a different format.
        os << " X" << XYZ[0] << " Y" << XYZ[1] << " Z" << XYZ[2];
    }
    else {
        os << "Vector(" << XYZ[0] << "," << XYZ[1] << "," << XYZ[2] << ")";
    }
}
Referenced by operator<<().
read()
void Vector::read (std::istream & is = std::cin)
Reads a Vector from input stream.
Read the vector from the input stream.
Parameters
is The input stream.
Definition at line 55 of file Vector.cpp.
                                {
    is >> XYZ[0] >> XYZ[1] >> XYZ[2];
}
Referenced by operator>>(), and STLFile::readSTLFile().
Friends And Related Symbol Documentation
operator>>
void operator>> (double & d, Vector const & v) [friend]
Streams the Z coordinate into the double.
Parameters
d The double to store the Z coordinate.
v The Vector to extract the Z coordinate from.
n The double variable to be assigned.
v The vector.
Definition at line 122 of file Vector.cpp.
                                            {
    n = v.XYZ[2];
}
The documentation for this class was generated from the following files:
STL_SLICER/include/Vector.h
STL_SLICER/src/Vector.cpp